### ISSUE TITLE
The task assumes "bolt" is in the path.

### ISSUE THREAD

**Issue by serialh0bbyist** [reidmv/reidmv-taskplan#2]
The task assumes that the "bolt" binary is in the path.

Pull request #1 allows the user to specify the "bolt_path" parameter to fix this.

**Comment by reidmv** [comment]
Rather than exposing a new user parameter, I've tried implementing an existing project's alternative approach to this issue. See https://github.com/reidmv/reidmv-taskplan/blob/0.1.2/tasks/init.rb#L20-L28.

The existing project is here: https://github.com/puppetlabs/puppetlabs-bolt_proxy/blob/master/tasks/init.rb.

This isn't as flexible as exposing bolt_path would be, but I think it should cover 90%+ of use cases, plus steer users to the preferred means of installing Bolt.

**Comment by serialh0bbyist** [comment]
I think this will work for what we were needing.

**Comment by frizop** [comment]
+1 on this
